// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVZejfnz72lTzD4_Mmo_gg8e8Kd9_oWQ',
    appId: '1:1017401228460:web:3fea586c665917e3ad7309',
    messagingSenderId: '1017401228460',
    projectId: 'plp-final-project-e4450',
    authDomain: 'plp-final-project-e4450.firebaseapp.com',
    storageBucket: 'plp-final-project-e4450.firebasestorage.app',
    measurementId: 'G-MMZW20SS05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEG5caPeJqhtbBJarJmba0moL0kaUazE',
    appId: '1:1017401228460:android:d796f750b1d87b62ad7309',
    messagingSenderId: '1017401228460',
    projectId: 'plp-final-project-e4450',
    storageBucket: 'plp-final-project-e4450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VDvYVl4hQSLzS2LG1nIZo8pVvY1QH_M',
    appId: '1:1017401228460:ios:4134ce98ce7efa20ad7309',
    messagingSenderId: '1017401228460',
    projectId: 'plp-final-project-e4450',
    storageBucket: 'plp-final-project-e4450.firebasestorage.app',
    iosBundleId: 'com.example.eduflash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1VDvYVl4hQSLzS2LG1nIZo8pVvY1QH_M',
    appId: '1:1017401228460:ios:4134ce98ce7efa20ad7309',
    messagingSenderId: '1017401228460',
    projectId: 'plp-final-project-e4450',
    storageBucket: 'plp-final-project-e4450.firebasestorage.app',
    iosBundleId: 'com.example.eduflash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWVZejfnz72lTzD4_Mmo_gg8e8Kd9_oWQ',
    appId: '1:1017401228460:web:e3832aee189c388bad7309',
    messagingSenderId: '1017401228460',
    projectId: 'plp-final-project-e4450',
    authDomain: 'plp-final-project-e4450.firebaseapp.com',
    storageBucket: 'plp-final-project-e4450.firebasestorage.app',
    measurementId: 'G-K5166FTQ42',
  );
}
